services:
  mini_indexer_postgres:
    container_name: mini_indexer_postgres
    image: 'postgres:13.6-alpine'
    environment:
      - POSTGRES_DB=mini_indexer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - 'mini-indexer-volume:/var/lib/postgresql/data'
    networks:
      - mini-indexer-net

  rails:
    build: .
    container_name: mini-indexer
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/mini-indexer
    ports:
      - "3000:3000"
    depends_on:
      - mini_indexer_postgres
    networks:
      - mini-indexer-net

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.data=/usr/share/elasticsearch/data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      - mini-indexer-net
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - mini-indexer-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  mini-indexer-net:
    driver: bridge

volumes:
  mini-indexer-volume:
    external: true
