default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('DB_HOST', 'mini-indexer-postgres') %>
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: mini_indexer_development

test:
  <<: *default
  database: mini_indexer_test
